### ISSUE TITLE
open an H5P file, clicking the expanding button displays empty content.

### ISSUE THREAD

**Issue by mhdosman** [UstadMobile/UstadMobile#802]
**Describe the bug**
open an H5P file, clicking the expanding button displays empty content.

**To Reproduce**
1. Go to course
2. Click on ePub content
3. click expand button
4. empty content is being shown

**Expected behavior**
Opening the content in a full screen mode, 

**Screenshots**
https://github.com/UstadMobile/UstadMobile/assets/153509442/a91a367c-9ff8-4b6e-9290-6395dabfe312

**Smartphone (please complete the following information):**
 - Device: Samsung A53

**Comment by mikedawson** [comment]
Might be resolvable with approach as per https://oliverbozhinovski.medium.com/fullscreen-youtube-video-in-webview-android-21f1c778cf56

**Comment by mhdosman** [comment]
well if that approach works with us, good we can try it.

**Comment by mikedawson** [comment]
Actually I think we have to change approach to using custom chrome tabs instead of a webview. 

![IMG_20240123_162239](https://github.com/UstadMobile/UstadMobile/assets/4280622/9772487a-a6b8-4d02-bd4f-1ce600a94371)

There is an Android bug that prevents H5P Video and Media working using the WebView request interceptor ( https://github.com/UstadMobile/UstadMobile/issues/814 ). There is another WebView issue bug that affects content that uses certain css units  ( https://github.com/UstadMobile/UstadMobile/issues/815 ) - where everything looks fine on the emulator, then just disappears on device. That affects content that is made with Articulate (Rise 360, likely others).

If we want to get the same results as the browser, we must "be" the browser. This change is being put in now, will be done shortly.

**Comment by mhdosman** [comment]
Given the current situation, it might be more beneficial to prioritize other tasks and work on this one in the next phase.

**Comment by mikedawson** [comment]
If this was only about H5P working in full-screen, then I'd definitely agree. Unfortunately, the exports from various popular eLearning tools are full of complex CSS and scripting. WebView used to be fine, but there are definitely now situations where what you see in Chrome and the WebView deviate. I already have a Chrome Tab based system implemented.

![Screenshot from 2024-01-24 12-27-06](https://github.com/UstadMobile/UstadMobile/assets/4280622/9bd2b745-1451-44a5-ab89-17933c198464)

(FYI the warning triangle will go away - the screenshot was using a test over a network IP address. When the IP address changes to using 127.0.0.1, then it turns into an info icon).

I think this will be done and ready to merge within the next few hours at most. We don't want a situation where someone loads a content piece (for whatever purpose use, demo to VIPs, etc) and then the screen just goes blank.

**Comment by mikedawson** [comment]
This is now fixed in version 0.4.15 using the new ChromeTab based system as per the pull request notes and doc updates.

https://github.com/UstadMobile/UstadMobile/assets/4280622/185f6933-7d34-43d1-b250-63b38abbc0f0

**Comment by mhdosman** [comment]
Still an issue with the latest version of the mobile app

https://github.com/UstadMobile/UstadMobile/assets/153509442/6dd063dd-c6b3-4b47-8f41-99f725916e3e

**Comment by mhdosman** [comment]
still an issue
https://github.com/UstadMobile/UstadMobile/assets/153509442/923d8306-c9fd-4d73-b4a4-476c2e6a4db8

**Comment by mikedawson** [comment]
> still an issue https://github.com/UstadMobile/UstadMobile/assets/153509442/923d8306-c9fd-4d73-b4a4-476c2e6a4db8

The latest version would open that content in a ChromeTab by default. The video shows opening it internally. This mean either 1) this was not checked with the latest version of the app or 2) the settings was changed away from the default.

@mhdosman  reply and let us know 1) what version exactly is being used (visible on the accounts list screen and login screen). and 2) if the settings have been changed to use internal webview instead of chrome tabs.

**Comment by mikedawson** [comment]
[h5p-running.webm](https://github.com/UstadMobile/UstadMobile/assets/4280622/e1ac6f7f-9c6b-4c3b-8c18-5aca5d7531fc)

@mhdosman thank you for the report, but we are not able to reproduce it. As per the video above, I tried importing the exact same file, opening it after import, then resetting the app, then opening it before download, whilst downloading, and after download (phone offline). All worked as expected.
